### ISSUE TITLE
SSL Zertifikate erstellen

### ISSUE THREAD

**Issue by LanceHWS** [NilsHWS/HWS-MQTT#18]
Dauer: bis zum 3.07

**Comment by oemerob** [comment]
1- Erzeugen vom privaten Schlüssel: C:\Users\barmanoe>openssl genpkey -algorithm RSA -out ca-private.key

2- Erzeugen eines Zertifikats: openssl req -new -x509 -sha256 -days 1200 -key ca-private.key -out ca-certificate.crt

3- Generieren eines privaten Schlüssel für Server: openssl genpkey -algorithm RSA -out server-private.key

4- Generieren eines CSR: openssl req -new -sha256 -key server-private.key -out server-csr.csr

5- Ezeugen eines Serverzertifikat: openssl x509 -req -sha256 -days 1200 -in server-csr.csr -CA ca-certificate.crt -CAkey ca-private.key -CAcreateserial -out server-certificate.crt

**Comment by oemerob** [comment]
![Image](https://github.com/NilsHWS/HWS-MQTT/assets/105221727/9a41aa1b-c39e-40b5-82b1-6e7ab0018f07)
![Image](https://github.com/NilsHWS/HWS-MQTT/assets/105221727/e92db1d2-94b7-43df-b7a4-9208b8016a31)
![Image](https://github.com/NilsHWS/HWS-MQTT/assets/105221727/d5c9b7df-f6fa-43f2-ac08-e8b786d4c79a)
![Image](https://github.com/NilsHWS/HWS-MQTT/assets/105221727/eaa7be90-dacf-4b8c-89cf-aada545105b3)
![Image](https://github.com/NilsHWS/HWS-MQTT/assets/105221727/940951fa-408f-44a4-b944-064b0a2ef389)
![Image](https://github.com/NilsHWS/HWS-MQTT/assets/105221727/424b853a-e2d4-446b-84bb-8777f3fef0d3)
![Image](https://github.com/NilsHWS/HWS-MQTT/assets/105221727/58726034-9251-4eda-8c99-bb72108e0248)
